// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpeol45m0x1kI5QQsikZteEjeV47Zz_CE',
    appId: '1:221667525181:web:a480b4f2969ff26d336054',
    messagingSenderId: '221667525181',
    projectId: 'rdp-todo',
    authDomain: 'rdp-todo.firebaseapp.com',
    storageBucket: 'rdp-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyfPjsnhpGYbkg3hVMacEqXFFRU1o0MtY',
    appId: '1:221667525181:android:68c7f7d258b76a72336054',
    messagingSenderId: '221667525181',
    projectId: 'rdp-todo',
    storageBucket: 'rdp-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAqb1BzL_s7TpVlrey3gKKCY_z6w55Md0',
    appId: '1:221667525181:ios:9026091f9e606980336054',
    messagingSenderId: '221667525181',
    projectId: 'rdp-todo',
    storageBucket: 'rdp-todo.appspot.com',
    iosClientId: '221667525181-cbknqj51oc2bjtkqdf43e3rksvog5k42.apps.googleusercontent.com',
    iosBundleId: 'com.example.basiclayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAqb1BzL_s7TpVlrey3gKKCY_z6w55Md0',
    appId: '1:221667525181:ios:9026091f9e606980336054',
    messagingSenderId: '221667525181',
    projectId: 'rdp-todo',
    storageBucket: 'rdp-todo.appspot.com',
    iosClientId: '221667525181-cbknqj51oc2bjtkqdf43e3rksvog5k42.apps.googleusercontent.com',
    iosBundleId: 'com.example.basiclayout',
  );
}
